driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1024

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[rackspace_apt]
  - name: debian-7
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[rackspace_ntp::default]
    attributes:
      ntp:
        sync_clock: true
        sync_hw_clock: true
  - name: undo
    run_list:
      - recipe[rackspace_ntp::undo]
